### ISSUE TITLE
"Proactive Email Notification Example " app

### ISSUE THREAD

**Issue by LC2121** [newmans99/Qlik-Proactive-Email-Notification-Example#1]
Hi, 

I can't find "Proactive Email Notification Example " app, 
Could you tell me where to download this app？

Thanks

**Comment by newmans99** [comment]
The proactive email example has not been completed yet. This the a simple email notification that provides the base for that example. For example, you will be able to setup rules and have emails generated. If you would like to participate in a community driven version please let me know and we can get started.
